### ISSUE TITLE
Equivalent of Bound for java -- trying to convert to java file??

### ISSUE THREAD

**Issue by madibalive** [stfalcon-studio/MultiImageView#1]
```
if (bitmaps.size() == 1) {
                Bitmap bitmap = scaleCenterCrop(bitmaps.get(0), bounds.width(), bounds.height()); // bound ??
                items.add(PhotoItem(bitmap, Rect(0, 0, bounds.width(), bounds.height())));
```
Currently need to extend your library ,having an issue with the conversion to java -- 
can find where bound arise from , what equivalent can i use , thanks

**Comment by bevzaanton** [comment]
Hi @madibalive ! In Java equivalent to ```bounds``` it is getter ```getBounds()```.

**Comment by madibalive** [comment]
hi thanks for the repley , could only access getClipBounds , i have uploaded what i got so far in my conversion, currently not working , can take a look and point me in the right direction.

[Gist url](https://gist.github.com/madibalive/2e697277ca62cfdcf29563adaeef1442)
thanks 

Ps i can close the issue if your want .

**Comment by bevzaanton** [comment]
MultiDrawable it is a class what extended from Drawable.
```
private static class MultiDrawable extends Drawable{
 ///overrided methods
}    
```

**Comment by madibalive** [comment]
thanks i didnt realise multimage , was different mutliDrawable
