### ISSUE TITLE
Cant able to add Multiple image urls from json response to adapter

### ISSUE THREAD

**Issue by siprabin** [stfalcon-studio/MultiImageView#3]
From Json response, I would like to add the 4 urls to multiimageview.

I used the following code to store the urls in arraylist:
```
details detail = new details();
if(jRealObject1.has("updatesFileCount")) {
                                String updatefilecount = jRealObject1.getString("updatesFileCount");
                                int count = Integer.parseInt(updatefilecount);
                                for (int k = 0; k < count; k++) {
                                    ls.add(jRealObject1.getString("updateFile"+k));
                                }
                                detail.setMultiimg(ls);
                            }
```
Here details is class for getter and setter method for setMultiimg()

And this is my adapter class:
 ```
List<String> ls = new ArrayList<String>(data.get(position).getMultiimg());
        StringBuilder sb = new StringBuilder();
        for (String s : ls)
        {
            sb.append(s);
            sb.append("\t");

            myHolder.multiImageView.addImage(BitmapFactory.decodeResource(Resources.getSystem(), Integer.parseInt(sb.toString())));
        }
```

By this the method, I used to call the value from my main activity.
But I get null value.

Kindly check the error in that coding. Or suggest me best solution to store to 

Waiting for your reply.

**Comment by demmydwi** [comment]
Hope this piece of code can help you @siprabin or someone out there.

```      
StrictMode.ThreadPolicy policy = new StrictMode.ThreadPolicy.Builder().permitAll().build();
StrictMode.setThreadPolicy(policy);
try {
    URL url = new URL("https://yourimageurl.jpg");
    yourMultiImageView.addImage(BitmapFactory.decodeStream(url.openStream()));
    yourMultiImageView.addImage(BitmapFactory.decodeStream(url.openStream()));
    yourMultiImageView.addImage(BitmapFactory.decodeStream(url.openStream()));
} catch (MalformedURLException e) {
    e.printStackTrace();
} catch (IOException e) {
    e.printStackTrace();
}
// Optional
yourMultiImageView.setShape(MultiImageView.Shape.CIRCLE);
```
Notes : i try to add 5 image, but fail (it shows blank image), i tought we can only add max 4 images for 1 MultiImageView.

**Comment by MohNage7** [comment]
my solution 


        public void setProductsImage(List<Product> productsList) {
            orderImgView.setShape(MultiImageView.Shape.RECTANGLE);//Rectangle with round corners
            for (int i = 0; i < productsList.size() && i < 5; i++) {
                new getBitmapImage().execute(productsList.get(i).getImage());
            }
        }

        class getBitmapImage extends AsyncTask<String, Void, Bitmap> {


            protected Bitmap doInBackground(String... urls) {
                try {
                    URL url = new URL(urls[0]);
                    HttpURLConnection connection = (HttpURLConnection) url.openConnection();
                    connection.setDoInput(true);
                    connection.connect();
                    InputStream input = connection.getInputStream();
                    return BitmapFactory.decodeStream(input);
                } catch (IOException e) {
                    e.printStackTrace();
                    return null;
                }

            }

            protected void onPostExecute(Bitmap bitmap) {
                orderImgView.addImage(bitmap);
            }
        }
